spring.datasource.url=jdbc:mysql://localhost:3306/erp?useSSL=false&serverTimezone=Asia/Kolkata
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

employee.service.url=http://103.205.65.27:8001/EmployeeService

springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false