spring.application.name=EmployeeService
server.port=9090

spring.messages.basename=messages
spring.messages.encoding=UTF-8

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Kolkata

logging.level.org.springframework=INFO
#  =====  Active Profile  =======
spring.profiles.active=dev
#spring.profiles.active=prod

management.endpoints.web.exposure.include=health,info

# Spring Security COMPLETELY disable — yahan JWT check nahi hota
# Gateway pe pehle hi validate ho chuka hai
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration,org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration